spring:
  datasource:
    cmn:
      #      jndi-name: java:comp/env/jdbc/cmnDS
      url: jdbc:mariadb://localhost:3306/cmnDB
      username: root
      password: test
      driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/config/cmn-mybatis-config.xml
  mapper-locations: classpath:mapper/cmn/**/*.xml
  type-aliases-package: fps.cmn.db.mapper




